<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PostgreSqlStore.fsi" />
    <Compile Include="PostgreSqlStore.fs" />
    <Compile Include="PostgreSqlObserverStore.fsi" />
    <Compile Include="PostgreSqlObserverStore.fs" />
    <Compile Include="PostgreSqlPilotStore.fs" />
    <EmbeddedResource Include="Migration.sql" />
    <EmbeddedResource Include="ObserverMigration.sql" />
    <EmbeddedResource Include="PilotMigration.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Persistence.Sql" />
    <PackageReference Include="FSharp.SystemTextJson" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FS.GG.Coordination.Core\FS.GG.Coordination.Core.fsproj" />
    <ProjectReference Include="..\FS.GG.Coordination.Orchestration.Observer\FS.GG.Coordination.Orchestration.Observer.fsproj" />
    <ProjectReference Include="..\FS.GG.Coordination.Orchestration.Pilot\FS.GG.Coordination.Orchestration.Pilot.fsproj" />
  </ItemGroup>
</Project>
