<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="OrganizationIssueFields.fsi" />
    <Compile Include="OrganizationIssueFields.fs" />
    <Compile Include="WorkTaxonomy.fsi" />
    <Compile Include="WorkTaxonomy.fs" />
    <Compile Include="Library.fsi" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FS.GG.Coordination.Protocol\FS.GG.Coordination.Protocol.fsproj" />
  </ItemGroup>

</Project>
