<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Transport.fsi" />
    <Compile Include="Transport.fs" />
    <Compile Include="IssueFields.fsi" />
    <Compile Include="IssueFields.fs" />
    <Compile Include="NativeRelations.fsi" />
    <Compile Include="NativeRelations.fs" />
    <Compile Include="ProjectAdapter.fsi" />
    <Compile Include="ProjectAdapter.fs" />
    <Compile Include="Library.fsi" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FS.GG.Coordination.Protocol\FS.GG.Coordination.Protocol.fsproj" />
    <ProjectReference Include="..\FS.GG.Coordination.Core\FS.GG.Coordination.Core.fsproj" />
  </ItemGroup>

</Project>
