<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Library.fsi" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FS.GG.Coordination.Protocol\FS.GG.Coordination.Protocol.fsproj" />
    <ProjectReference Include="..\FS.GG.Coordination.Core\FS.GG.Coordination.Core.fsproj" />
  </ItemGroup>

</Project>
