<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.Web" />
  <ItemGroup>
    <ProjectReference Include="../FS.GG.Coordination.Protocol/FS.GG.Coordination.Protocol.fsproj" />
    <ProjectReference Include="../FS.GG.Coordination.Core/FS.GG.Coordination.Core.fsproj" />
    <ProjectReference Include="../FS.GG.Coordination.GitHub/FS.GG.Coordination.GitHub.fsproj" />
  </ItemGroup>
</Project>
